baseurl = "https://hugoblog.zhaohuabing.com/"
title = "Huabing Blog"
theme = "hugo-nederburg-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = "zhaohuabings-blog"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[params]
  header_image = "https://img.zhaohuabing.com/home-bg-jeep.jpg"
  slogan = "路在脚下，心向远方"
  description = "Huabing Blog" # meta description
  author = "赵化冰"
  authorLink = "https://appernetic.io/"
  bio = [
    "Huabing Zhao (赵化冰) is a software developer, an open source enthusiast and a life adventurer."
  ]
  copyright = [
    "&copy; 2018 Huabing Zhao",
    "",
    ""
  ]

  # Sidebar settings
  sidebar = true                           # whether or not using Sidebar.
  sidebar_about_description = "Software Developer, Open Source Enthusiast and Life Adventurer"
  sidebar_avatar = "/img/avatar-zhaohuabing.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 2 

  #disqus
  disqus_username = "zhaohuabings-blog"
  
  [params.social]
  rss            = true 
  email          = "zhaohuabing@gmail.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  linkedin       = "https://www.linkedin.com/in/zhaohuabing"
  stackoverflow  = "https://stackoverflow.com/users/2306565/huabing-zhao"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/zhaohuabing"
  wechat         = "https://zhaohuabing.com/img/wechat_qrcode.jpg"
  #pinterest     = "full profile url in pinterest"
  
  [[params.friend_link]]
  title = "Linda的博客"
  href =  "https://zhaozhihan.com"

  [[params.bookmark_link]]
  title =  "Martin Fowler"
  href =  "https://martinfowler.com"
  [[params.bookmark_link]]
  title = "ServiceMesh中文网"
  href =  "http://www.servicemesh.cn"
  [[params.bookmark_link]]
  title = "Awesome Service Mesh"
  href = "https://servicemesh.gitbooks.io/awesome-servicemesh/"
  [[params.bookmark_link]]
  title =  "Image Compression"
  href = "https://tinypng.com/"
